---
title: "badface_clear"
output: word_document
---

**讀檔案**

```{r}
library(readr)
data<-read_csv("C:/Users/student/Desktop/專題/all_rate.csv")
face<-data 
```

**絕對值(右臉寬-左臉寬)** 
```{r}
face$profile<-abs(face$face_R_width_W-face$face_L_width_W) 
```
**看前5筆**
```{r}
head(face$profile)  
```
**側臉數值的直方圖**
```{r}
hist(face$profile)
```
**把臉部比例差大於0.2的刪掉,只留<0.2的**
```{r}
newface<-subset(face,face$profile<0.2)
```
**用新臉來處理眼睛**
```{r}
newface$eyebigsmall<-newface$Eye_R_H4_L/newface$Eye_L_H4_L
```

**畫圖(眼睛大小眼差距過大)**

```{r}

hist(newface$eyebigsmall)
```
**新資料表(大小眼用0.8<x<1.2過濾)**
```{r}
newfaceeye<-subset(newface,newface$eyebigsmall>0.8&newface$eyebigsmall<1.2) 
```
```{r}
hist(newfaceeye$eyebigsmall)
```



**右眼分布圖**
```{r}
hist(newfaceeye$Eye_R_H4_L)
```
**對左右閉眼只留0.009以上的**
```{r}
newfaceeyesleep<-subset(newfaceeye,newfaceeye$Eye_R_H4_L>0.009)
newfaceeyesleep<-subset(newfaceeyesleep,newfaceeyesleep$Eye_L_H4_L>0.009)
```

**最終各類別的筆數**
1.原本各Label的數量
```{r}
ftable(face$Label)
```
2.調整後的數量
```{r}
ftable(newfaceeyesleep$Label)
```
3.刪除的數量
```{r}
ftable(face$Label)-ftable(newfaceeyesleep$Label)
```
**匯出csv**
```
write.csv(newfaceeyesleep,"all_clear_rate_p.csv",fileEncoding = "UTF-8")
```
